Console.WriteLine("Введите коордитаты точки А.");
Console.WriteLine("Если точка находится в плоскости XY, то в поле ввода координаты по оси Z (za) следует уаказать 0.");
Console.WriteLine("Если точка находится в плоскости YZ, то в поле ввода координаты по оси X (xa) следует уаказать 0.");
Console.WriteLine("Если точка находится в плоскости XZ, то в поле ввода координаты по оси Y (ya) следует уаказать 0.");
Console.Write("Введите координату X для точки А, xa = ");
double xa = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Y для точки А, ya = ");
double ya = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Z для точки А, za = ");
double za = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите коордитаты точки B.");
Console.WriteLine("Если точка находится в плоскости XY, то в поле ввода координаты по оси Z (zb) следует уаказать 0.");
Console.WriteLine("Если точка находится в плоскости YZ, то в поле ввода координаты по оси X (xb) следует уаказать 0.");
Console.WriteLine("Если точка находится в плоскости XZ, то в поле ввода координаты по оси Y (yb) следует уаказать 0.");
Console.Write("Введите координату X для точки B, xb = ");
double xb = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Y для точки B, yb = ");
double yb = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Z для точки B, zb = ");
double zb = Convert.ToInt32(Console.ReadLine());
double xabpow = Math.Pow((xb - xa), 2);
double yabpow = Math.Pow((yb - ya), 2);
double zabpow = Math.Pow((zb - za), 2);
double distance = Math.Sqrt(xabpow + yabpow + zabpow);
Console.WriteLine("Расстояние между точками A и B равно: " + distance);